version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "4200:4200"
    depends_on:
      [api,webapi]

  api:
    build:
      context: ./nodeapi
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      [emongo]

  webapi:
    build:
      context: ./javaapi
      dockerfile: Dockerfile
    container_name: webapi
    ports:
      - "9000:9000"
    depends_on:
      [emartdb]

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    command: ["nginx-debug", "-g", "daemon off;"]
    depends_on:
       [client]
    
  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:5.7
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
